name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version
      with:
        fetch-depth: 0  # Ensures full git history

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'  # Latest stable Ruby version
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        npm install -g mermaid.cli

    - name: Setup Git config
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Build and Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status
        bash bin/deploy --verbose \
          ${{ github.event_name == 'pull_request' && '--no-push' || '' }} \
          --src ${{ github.ref_name }} \
          --deploy gh-pages